屏蔽的是自己实现相应交易代码函数，需要修改的打开修改即可

common=require("common")


-- waitAction = function()
	-- local mapName=""
	-- local mapNum=0
-- ::begin::
	-- 等待空闲()
	-- mapName = 取当前地图名()
	-- mapNum =取当前地图编号()
	-- if (mapName=="艾尔莎岛" or mapName=="法兰城" or mapName=="里谢里雅堡" )then	
		-- common.gotoFalanBankTalkNpc()
		-- goto bankWait
	-- elseif (mapName=="银行" and mapNum== 1121)then	
		-- goto bankWait
	-- elseif (mapName=="召唤之间" )then	--登出 bank
		-- 移动(3,9)
		-- 对话选是(4,9)
		-- 回城()
		-- common.gotoFalanBankTalkNpc()
		-- goto bankWait
	-- end	
	-- 回城()
	-- 等待(1000)	
	-- goto begin
-- ::bankWait::
	-- if(取当前地图编号() ~= 1121)then
		-- common.gotoFalanBankTalkNpc()
	-- end
	-- if(common.getTableSize(全部宠物信息()) == 5)then
		-- 移动(11,8)
		-- 面向("东")
		-- 等待服务器返回()
		-- if(银行("宠物数") == 5)then	--默认20
			-- goto saveData
		-- end
	-- end	

	-- if(取当前地图名() ~= "银行")then goto dengru end
	-- 移动(10,12)
	-- topicMsg = {name=人物("名称"),pets=5-common.getTableSize(全部宠物信息()),line=人物("几线")}
	-- 发布消息("烈风哥布林仓库信息", common.TableToStr(topicMsg))
	-- if(银行("金币") >= 1000000)then
		-- if(人物("金币") > 998000)then
			-- 等待交易("","金币:2000","",20000)
		-- else
			-- 等待交易("","","",20000)
		-- end
	-- else
		-- if(人物("金币") > 900000)then		
			-- goto cun
		-- else
			-- 等待交易("","","",20000)
		-- end
	-- end	
	-- if(common.getTableSize(全部宠物信息()) == 5)then
		-- goto cun
	-- end
	-- goto bankWait
-- ::cun::
	-- 移动(11,8)
	-- 面向("东")
	-- 等待服务器返回()
	-- bankGold = 银行("金币")
	-- cGold=人物("金币")
	-- if(bankGold > 1000000)then	--银行金币大于100万 取最小值
		-- cGold =  math.min(10000000-bankGold,cGold)
	-- else
		-- cGold =  math.min(1000000-bankGold,cGold-2000)
	-- end
	-- 银行("存钱",cGold)
	-- 等待(2000)
	-- 银行("取钱",2000)
	-- if(银行("宠物数") == 5)then	--默认20
		-- if(common.getTableSize(全部宠物信息()) == 5)then
			-- return
		-- end
	-- else
		-- i=0
		-- while i<= 5 do
			-- 银行("存宠",i)
			-- i=i+1
			-- 等待(1000)
		-- end
	-- end
	-- goto bankWait	
-- end
-- common.warehouseOnlineWait("烈风哥布林仓库.txt",waitAction)
common.warehouseOnlineWait("烈风哥布林仓库.txt",common.waitTradePetsAction,{x=10,y=12,topic="烈风哥布林仓库信息"})